// Shared request-input validators for the account-data API routes. Activity
// ids are generated by the content pipeline as lowercase slug-like strings
// (e.g. "switzerland--bivouac-..."), so this both rejects obvious garbage
// early and caps size against a client sending something huge.
const ACTIVITY_ID_RE = /^[a-z0-9-]{1,200}$/;
const MAX_REVIEW_TEXT_LENGTH = 2000;
const MAX_SYNC_LIST_LENGTH = 500;

// Deliberately permissive (not RFC 5322) — just enough to reject obvious
// typos/garbage before a human reads it in the admin inquiries view.
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const MAX_SHORT_FIELD_LENGTH = 200;
const MAX_INQUIRY_MESSAGE_LENGTH = 4000;

export function isValidShortText(value: unknown, maxLength = MAX_SHORT_FIELD_LENGTH): value is string {
  return typeof value === "string" && value.trim().length > 0 && value.length <= maxLength;
}

export function isValidEmail(value: unknown): value is string {
  return typeof value === "string" && value.length <= MAX_SHORT_FIELD_LENGTH && EMAIL_RE.test(value);
}

export function isValidInquiryMessage(value: unknown): value is string {
  return typeof value === "string" && value.length <= MAX_INQUIRY_MESSAGE_LENGTH;
}

export function isValidActivityId(value: unknown): value is string {
  return typeof value === "string" && ACTIVITY_ID_RE.test(value);
}

export function isValidRating(value: unknown): value is number {
  return typeof value === "number" && Number.isInteger(value) && value >= 1 && value <= 5;
}

export function isValidReviewText(value: unknown): value is string {
  return typeof value === "string" && value.length <= MAX_REVIEW_TEXT_LENGTH;
}

export function isValidSyncFavorites(value: unknown): value is string[] {
  return (
    Array.isArray(value) &&
    value.length <= MAX_SYNC_LIST_LENGTH &&
    value.every((id) => isValidActivityId(id))
  );
}

export function isValidSyncReviews(
  value: unknown
): value is Record<string, { rating: number; text: string; updatedAt: string }> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const entries = Object.entries(value as Record<string, unknown>);
  if (entries.length > MAX_SYNC_LIST_LENGTH) return false;
  return entries.every(([activityId, review]) => {
    if (!isValidActivityId(activityId)) return false;
    if (typeof review !== "object" || review === null) return false;
    const r = review as Record<string, unknown>;
    return (
      isValidRating(r.rating) &&
      isValidReviewText(r.text) &&
      typeof r.updatedAt === "string" &&
      r.updatedAt.length <= 64
    );
  });
}
